name: Deploy from performance branch

on:
  push:
    branches:
      - performance

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout performance branch
        uses: actions/checkout@v4
        with:
          ref: performance

      - name: deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
